services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:f5bOvvcoW+WLBOijXBFcbTbxnhdq/KAzAFqH7qlur/U=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-backend.onrender.com
